2021-11-18 20:30:04,628 ERROR: Exception on /user/Bob [GET] [in /Users/andrey/Projects/flask_project/venv/lib/python3.9/site-packages/flask/app.py:1457]
Traceback (most recent call last):
  File "/Users/andrey/Projects/flask_project/venv/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/andrey/Projects/flask_project/venv/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/andrey/Projects/flask_project/venv/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/andrey/Projects/flask_project/venv/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/andrey/Projects/flask_project/venv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/andrey/Projects/flask_project/app/routes.py", line 92, in user
    return render_template('user.html', user=user, posts=posts, form=form)
  File "/Users/andrey/Projects/flask_project/venv/lib/python3.9/site-packages/flask/templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/Users/andrey/Projects/flask_project/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/Users/andrey/Projects/flask_project/venv/lib/python3.9/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/Users/andrey/Projects/flask_project/venv/lib/python3.9/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/Users/andrey/Projects/flask_project/venv/lib/python3.9/site-packages/jinja2/loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "/Users/andrey/Projects/flask_project/venv/lib/python3.9/site-packages/jinja2/environment.py", line 757, in compile
    self.handle_exception(source=source_hint)
  File "/Users/andrey/Projects/flask_project/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/andrey/Projects/flask_project/app/templates/user.html", line 12, in template
    <p>{{ user.followers.count() }} followers, {{ user.followed.count() follow: }}</p>
jinja2.exceptions.TemplateSyntaxError: expected token 'end of print statement', got 'follow'
2021-11-18 20:41:19,363 INFO: Microblog startup [in /Users/andrey/Projects/flask_project/app/__init__.py:53]
2021-11-18 20:45:39,330 INFO: Microblog startup [in /Users/andrey/Projects/flask_project/app/__init__.py:53]
2021-11-19 10:31:48,777 INFO: Microblog startup [in /Users/andrey/Projects/flask_project/app/__init__.py:53]
2021-11-19 10:32:10,420 INFO: Microblog startup [in /Users/andrey/Projects/flask_project/app/__init__.py:53]
